version: "3"
# services 에서 여러 서비스를 정의
services:
  # nextjs 서비스 정의
  nextjs:
    # 현재 디렉토리(.)에 있는 Dockerfile을 사용해서 이미지 빌드
    build: .
    networks:
      - app_network
    # 주의: nextjs 서비스에는 ports 대신 expose를 사용하여 외부에서 직접 접근하지 못하도록 설정합니다.
    expose:
      - 3000
    # 외부에서 직접 접근 불가능하도록 ports 설정 제거

  # nginx 서비스 정의
  nginx:
    # docker hub의 nginx image를 사용
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nextjs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge